services:
  spamassassin:
    image: axllent/spamassassin
    ports:
      - "783:783"
    restart: always
    environment:
      - DNS_CHECKS=1
    volumes:
      - spamassassin_data:/var/lib/spamassassin

  rspamd:
    image: rspamd/rspamd:latest
    ports:
      - "11333:11333"

volumes:
  spamassassin_data: {}
